# HUSK или ZOMBIE
zombie-type: HUSK

# Может ли зомби, появляющийся на месте смерти игрока, подбирать вещи
zombie-can-pickup-items: false

# Кулдаун между появлениями зомби после смерти игрока (в секундах)
# Если игрок умирает чаще, чем указано здесь, зомби будет появляться только раз в указанное время
# Например, если игрок умирает каждые 5 сек, а лимит 10 сек, то зомби появится только раз в 10 сек
# Установите 0 для отключения лимита (зомби будет появляться после каждой смерти, если шанс позволяет)
zombie-spawn-cooldown: 10

# Шанс появления зомби после смерти игрока (в процентах от 0 до 100)
# Например, 50 означает 50% шанс, 100 - всегда появляется, 0 - никогда не появляется
zombie-spawn-chance: 50
